$file_title should not be a WikiPage object
After running the following command:

  php extensions/SemanticMediaWiki/maintenance/rebuildData.php -d 5 -v

the following error occurred:

> (1283/230174) Processing ID 1356 ...
> (1284/230174) Processing ID 1357 ...
> (1285/230174) Processing ID 1358 ...
> (1286/230174) Processing ID 1359 ...
> PHP Fatal error:  Call to undefined method WikiFilePage::getArticleID() in /opt/meza/htdocs/mediawiki/extensions/ApprovedRevs/includes/ApprovedRevsHooks.php on line 992

> Fatal error: Call to undefined method WikiFilePage::getArticleID() in /opt/meza/htdocs/mediawiki/extensions/ApprovedRevs/includes/ApprovedRevsHooks.php on line 992

This occurred because while the `BeforeParserFetchFileAndTitle` hook was
passing in a `Title` object as expected, the first if-statement of the hook
handler function potentially set it to a `WikiPage` object. This change removes
that possibility.